In [4]:
import pandas as pd

In [14]:
widths = [6, 14, 13, 10]
df_f = pd.read_fwf("f_poa.txt", header=None, index_col=0)
df_m = pd.read_fwf("m_poa.txt", header=None, index_col=0)

In [17]:
pd.concat([df_m,df_f])

,1,2,3,4,5,6,7,8,9,10,11
0,,,,,,,,,,,
1,35,JURANDYR COUTO JUNIOR,JP/TREINAMENTO/RUNNI,2:21:41,3:22,1:08:53,3:16,1:12:49,3:28,1:39:21,1:56:20
2,6,ALLISON ROCHA PERES,CIA DOS CAVALOS,2:23:17,3:24,1:11:50,3:25,1:11:27,3:24,1:41:36,1:58:24
3,34,MARCOS ALEXANDRE ELIAS,NaN,2:23:55,3:25,1:11:48,3:25,1:12:08,3:26,1:41:48,1:58:31
4,9,EBERTH DA SILVA SILVéRIO,FRITAR/O2 FIT,2:24:49,3:26,1:11:49,3:25,1:13:00,3:28,1:41:51,1:58:50
5,2,LUIS FELIPE LEITE BARBOZA,VERTICAL PILATES,2:26:29,3:29,1:11:50,3:25,1:14:39,3:33,1:42:12,1:59:43
...,...,...,...,...,...,...,...,...,...,...,...
852,4716,CABRERA,DANIELA,6:11:38,8:49,2:48:26,7:59,3:23:13,9:38,NaN,4:57:34
853,509,KELLEN GOMES DE SOUZA ALMEIDA PADRO,VAMOS QUE VAMOS,6:14:00,8:52,2:54:57,8:18,3:19:04,9:27,NaN,5:04:42
854,3937,RENATA ALVES DE ALMEIDA,REGINA LIMA,6:15:06,8:54,2:53:53,8:15,3:21:13,9:33,NaN,5:04:42
855,876,IVELISE GIAROLLA,NOVA EQUIPE,6:20:46,9:02,2:54:59,8:18,3:25:48,9:46,NaN,5:08:24
856,933,ANDRESSA SOARES,RUN4SAVE,6:29:54,9:15,2:41:11,7:39,3:48:43,0:51,NaN,5:16:48